#! /usr/bin/env bash
# Copyright 2014 Tom Regan
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

NAME=bosh

[[ -z $BOSH_HOME ]] && {
    echo -e "$NAME: set BOSH_HOME to the bosh install location\n\texport BOSH_HOME=..."
    exit 1
}

require() {
    local call=$1; shift
    source $BOSH_HOME/core/require/$call.sh $@
}
install() {
    local call=$1; shift
    local script=$BOSH_HOME/install/$call.sh
    [[ ! -f $script ]] && {
	warn "No installer for $call"
    } || {
	source $script $@
    }
}
configure() {
    local package=$1; shift 2
    local configuration=$1; shift
    source $BOSH_HOME/configure/$package.sh 2> /dev/null && {
	$configuration $@ 2> /dev/null
    } || {
	fail "No such configuration '$configuration' for $package"
	exit 1
    }
}
package() {
    local call=$1; shift
    source $BOSH_HOME/core/package/$call.sh "$@"
}
include() {
    [[ -f $BOSH_HOME/$1 ]] && source $BOSH_HOME/$1 || {
	[[ -f $BOSH_HOME/$1.sh ]] && source $BOSH_HOME/$1.sh || {
	    fail "'include $1' failed because $1 could not be found"
	    exit 1
	}
    }
}
export -f require install configure package include

init() {
    source $BOSH_HOME/core/out.sh
    source $BOSH_HOME/core/environment.sh

    ARGS=$@
    for ARG in $ARGS; do
	[[ $ARG == '-r' || $ARG == '--remote' ]] && {
	    ARGS="${ARGS/-r/}";ARGS="${ARGS/--remote/}"
	    REMOTE=true
	}
    done
    [[ -z $REMOTE ]] || {
	$BOSH_HOME/core/remote.sh $ARGS
	exit 0
    }
}

run() {
    warn "Bosh is currently under development"
    if [[ -f $BOSH_HOME/run/$1.sh ]]; then
	if [ -x $BOSH_HOME/run/$1.sh ]; then
	    $BOSH_HOME/run/$1.sh
	else
	    fail "$1.sh is not executable"
	    exit 1
	fi
    elif [[ -f $BOSH_HOME/run/$1 ]]; then
	if [ -x $BOSH_HOME/run/$1 ]; then
	    $BOSH_HOME/run/$1
	else
	    fail "$1 is not executable"
	    exit 1
	fi
    else
	fail "Script not found: ${1:-(because no script was specified)}"
	exit 1
    fi
}

init $@

run $@
